import Head from "next/head";
import SearchBox from "../components/SearchBox";
import axios from "axios";
import styles from "../styles/Home.module.scss";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap"
          rel="stylesheet"
        ></link>
        <title>Pokedex</title>
      </Head>
      <div className={styles.inner_container}>
        <h1 className={styles.title}>Pokedex</h1>
        <SearchBox />
      </div>
    </div>
  );
}
